info:
  app:
    version: 1.1
    name: Testing spring boot actuator
    description: Spring boot actuator
#to expose other endpoints
management:
  #if this property is not enabled. all custom info declared up will not be shown
  info:
    env:
      enabled: true
  endpoint:
    health:
      # to show more details in the health endpoint
      show-details: always
  endpoints:
    web:
      # use this property to change the base url for the actuator
      # base-path: /custom-url #localhost:8080/custom-url
      exposure:
        #you can include or exclude the endpoints as you want.
        include: "*" #the wildcard * means all